const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const base=process.env.SITE_URL||'http://127.0.0.1:8769/',out=process.env.TEST_OUTPUT||'/tmp/prostate-browser-tests';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),headless:true});
const results={tested_at:new Date().toISOString(),checks:[],errors:[]};
function ok(k,v){if(!v)throw Error(k);results.checks.push(k)}
const p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>results.errors.push(String(e)));await p.goto(base);await p.waitForSelector('.card');ok('desktop_count',(await p.locator('#stats').innerText()).includes('175'));ok('desktop_no_horizontal_overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:out+'/desktop.png',fullPage:false});
await p.locator('#search').fill('PEACE V-STORM');await p.waitForTimeout(100);ok('trial_search',await p.locator('.card').count()>2);await p.locator('#reset').click();await p.locator('#f-type').selectOption('随机试验/报告');await p.locator('#f-rt').selectOption('ENRT/WPRT');ok('combined_filters',await p.locator('.card').count()>0);await p.locator('#reset').click();await p.locator('#search').fill('999999999999999');ok('no_false_positive_identifier',(await p.locator('#content').innerText()).includes('没有符合'));await p.locator('#reset').click();
await p.goto(base+'#view=new');ok('new_collection_24',(await p.locator('#resultcount').innerText()).startsWith('24'));
const data=await p.locator('#appdata').textContent();const lib=JSON.parse(data).library;
for(const r of lib){await p.goto(base+'#paper='+r.id);await p.waitForSelector('.detail h1');const text=await p.locator('#detail').innerText();ok('detail_'+r.seed_id,text.includes(r.notes.findings[0])&&text.includes(r.notes.limitations));}
await p.goto(base+'#paper='+lib.find(x=>x.seed_id==='C009').id);await p.screenshot({path:out+'/detail.png',fullPage:true});ok('80_percent_interval',(await p.locator('#detail').innerText()).includes('80%CI'));ok('all_article_links_https',await p.locator('#detail a[target]').evaluateAll(a=>a.every(x=>x.href.startsWith('https://'))));
await p.goto(base+'#view=latest');ok('latest_update_entry',(await p.locator('#resultcount').innerText()).includes('本次运行新增'));await p.goto(base+'#view=maintenance');ok('maintenance_status',(await p.locator('#content').innerText()).includes('最近完整成功更新'));await p.goto(base+'#view=coverage');ok('coverage_matrix',(await p.locator('tbody tr').count())===7);await p.goto(base+'#view=candidates');ok('candidate_separation',(await p.locator('#content').innerText()).includes('尚未形成已核对中文结论'));
await p.setViewportSize({width:390,height:844});await p.goto(base+'#view=all');await p.waitForSelector('.card');ok('mobile_no_horizontal_overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#menu').click();ok('mobile_menu_visible',await p.locator('#sidebar').isVisible());await p.locator('#navigation [data-view="B"]').click();ok('mobile_chapter_jump',(await p.locator('#viewtitle').innerText()).includes('pN1'));ok('mobile_menu_closed',!(await p.locator('#sidebar').isVisible()));await p.screenshot({path:out+'/mobile.png',fullPage:false});await p.locator('.readbutton').first().click();ok('mobile_note_open',await p.locator('.detail h1').isVisible());ok('mobile_detail_no_overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await p.goto('file://'+root+'/public/index.html');ok('offline_snapshot',await p.locator('.card').count()>0);ok('no_javascript_errors',results.errors.length===0);
results.passed=true;fs.writeFileSync(out+'/ui_report.json',JSON.stringify(results,null,2));console.log(JSON.stringify({passed:true,checks:results.checks.length,errors:results.errors}));await browser.close();
