from common import *
pm_prostate='("Prostatic Neoplasms"[MeSH Terms] OR prostate[Title/Abstract] OR prostatic[Title/Abstract])'
pm_nodes='("node-positive"[Title/Abstract] OR "node positive"[Title/Abstract] OR "lymph node metastas*"[Title/Abstract] OR "nodal metastas*"[Title/Abstract] OR "nodal recurren*"[Title/Abstract] OR "lymph node recurren*"[Title/Abstract] OR cN1[Title/Abstract] OR pN1[Title/Abstract] OR M1a[Title/Abstract])'
pm_rt='(radiotherap*[Title/Abstract] OR "radiation therapy"[Title/Abstract] OR irradiation[Title/Abstract] OR SBRT[Title/Abstract] OR SABR[Title/Abstract] OR ENRT[Title/Abstract])'
ep_prostate='(TITLE_ABS:prostate OR TITLE_ABS:prostatic)'
ep_nodes='(TITLE_ABS:"node-positive" OR TITLE_ABS:"node positive" OR TITLE_ABS:"lymph node metastasis" OR TITLE_ABS:"lymph node metastases" OR TITLE_ABS:"nodal metastasis" OR TITLE_ABS:"nodal metastases" OR TITLE_ABS:"nodal recurrence" OR TITLE_ABS:"lymph node recurrence" OR TITLE_ABS:cN1 OR TITLE_ABS:pN1 OR TITLE_ABS:M1a)'
ep_rt='(TITLE_ABS:radiotherap* OR TITLE_ABS:"radiation therapy" OR TITLE_ABS:irradiation OR TITLE_ABS:SBRT OR TITLE_ABS:SABR OR TITLE_ABS:ENRT)'
branches=[('broad','全主题交集','',''),('initial','初诊N1','(cN1[Title/Abstract] OR definitive[Title/Abstract] OR "newly diagnosed"[Title/Abstract])','(TITLE_ABS:cN1 OR TITLE_ABS:definitive OR TITLE_ABS:"newly diagnosed")'),('postoperative','前列腺切除术后','(prostatectom*[Title/Abstract] OR postoperative[Title/Abstract])','(TITLE_ABS:prostatectom* OR TITLE_ABS:postoperative)'),('recurrent','复发/持续','(recurren*[Title/Abstract] OR salvage[Title/Abstract] OR persist*[Title/Abstract])','(TITLE_ABS:recurren* OR TITLE_ABS:salvage OR TITLE_ABS:persist*)'),('technique','照射范围技术毒性','(dose[Title/Abstract] OR toxicity[Title/Abstract] OR "elective nodal"[Title/Abstract] OR "whole pelvis"[Title/Abstract] OR reirradiation[Title/Abstract])','(TITLE_ABS:dose OR TITLE_ABS:toxicity OR TITLE_ABS:"elective nodal" OR TITLE_ABS:"whole pelvis" OR TITLE_ABS:reirradiation)'),('guidelines','指南及综述','(guideline[Publication Type] OR review[Publication Type] OR consensus[Title/Abstract])','(PUB_TYPE:review OR TITLE_ABS:guideline OR TITLE_ABS:consensus)')]
queries=[]
for key,label,pm,ep in branches:queries.append({'id':key,'label':label,'pubmed':' AND '.join(x for x in [pm_prostate,pm_nodes,pm_rt,pm] if x),'europepmc':' AND '.join(x for x in [ep_prostate,ep_nodes,ep_rt,ep] if x)})
trials=['PEACE V','PEACE V-STORM','OLIGOPELVIS','PLATIN','PROPER trial','PROPER study','PRIMENOD','PROQURE','POINTER-PC','PRIME trial']
queries.append({'id':'trials','label':'关键试验追踪','pubmed':pm_prostate+' AND ('+' OR '.join('"'+t+'"[Title/Abstract]' for t in trials)+')','europepmc':ep_prostate+' AND ('+' OR '.join('TITLE_ABS:"'+t+'"' for t in trials)+')'})
cfg={'schema_version':1,'topic':'前列腺癌＋淋巴结转移＋放疗','timezone':'Asia/Shanghai','schedule_utc':'17 1 * * 1','lookback_days':90,'monthly_history':True,'stale_after_days':9,'site_url':None,'deployment':'not_configured','query_version':'2026-09-14.2','queries':queries,'trial_names':trials,'sections':{'A':'初诊淋巴结阳性的根治性放疗','B':'前列腺切除术后pN1放疗','C':'淋巴结复发及持续病灶的放疗','D':'照射范围、剂量、技术与毒性','G':'指南共识与证据综述','F':'试验方案与研究设计','E':'混合人群与治疗情境的补充证据'},'unconnected_sources':['Embase','Web of Science','知网','万方']}
atomic(ROOT/'config/search.json',cfg)
if __name__=='__main__':print('configuration written')
